### ISSUE TITLE
Use Docker 1.9+

### ISSUE THREAD

**Issue by surdy** [dcos/dcos-vagrant-box#3]
[DCOS system requirements](https://dcos.io/docs/1.7/administration/installing/custom/system-requirements/) specify Docker 1.9+ as a requirement. But dcos-vagrant uses docker 1.8.2 

Please update the dcos-vagrant-box to use Docker 1.9

**Comment by karlkfi** [comment]
dcos-vagrant-box 0.5.0 has docker 1.11
